### ISSUE TITLE
Link to included document not working.

### ISSUE THREAD

**Issue by jmini** [asciidoctor/docgist#18]
I am not sure what the [safe mode](http://asciidoctor.org/docs/user-manual/#running-asciidoctor-securely) used by `gist.asciidoctor.org` is.

I am trying to render this document:

* [Page](https://github.com/BSI-Business-Systems-Integration-AG/scoutbook/blob/asciidoc/build/scout_helloworld/src/docs/scout_helloworld.adoc) on GitHub
* [Raw content](https://raw.githubusercontent.com/BSI-Business-Systems-Integration-AG/scoutbook/asciidoc/build/scout_helloworld/src/docs/scout_helloworld.adoc) on GitHub
* [Preview](http://gist.asciidoctor.org/?github-BSI-Business-Systems-Integration-AG%2Fscoutbook%2Fasciidoc%2F%2Fbuild%2Fscout_helloworld%2Fsrc%2Fdocs%2Fscout_helloworld.adoc) in `gist.asciidoctor.org`

The includes are replaced by links, maybe because we the `safe mode` is set to `secure`. This is Ok for me.

It would be great to have the links working and pointing to the corresponding page in the `gist.asciidoctor.org` preview.

For example the first link `../../../../adoc/CreateNewProject.adoc` should point to the preview page [adoc/CreateNewProject.adoc](http://gist.asciidoctor.org/?github-BSI-Business-Systems-Integration-AG%2Fscoutbook%2Fasciidoc%2F%2Fadoc%2FCreateNewProject.adoc).

**Comment by nawroth** [comment]
This is a good suggestion. Based on the work with the images, it shouldn't be too hard to implement.

**Comment by mojavelinux** [comment]
I think it's reasonable to assume we can get includes working (filed as #11). The link feature is really only intended to be used on GitHub where we have no authority to enable includes (so we needed to provide a concession in the interim).

**Comment by nawroth** [comment]
Right, rewriting the links would just be a temporary fix until we get includes working. Getting those working is a larger piece of work though.

**Comment by mojavelinux** [comment]
> rewriting the links would just be a temporary fix until we get includes working.

Totally reasonable.

**Comment by nawroth** [comment]
The URLs get quite crazy when browsing into folders, that should be fixed at some point.

**Comment by nawroth** [comment]
Example: http://goo.gl/1pGe3B

**Comment by mojavelinux** [comment]
Are you referring to recursive includes? If so, there is a parameter to guard against this. max-include-depth I think.

**Comment by nawroth** [comment]
It doesn't resolve `../` etc in URLs, but just appends it which works but makes the URL very long, especially after some browsing. Example: http://gist.asciidoctor.org/?github-asciidoctor%2Fdocgist%2F%2Fgists%2Fincludes%2F..%2Fincludes%2F..%2Fincludes%2F..%2Fincludes%2F..%2Fincludes%2F..%2Fincludes%2F..%2Fincludes%2F..%2Fincludes%2F..%2Fincludes.adoc
I'm surprised it works!

**Comment by mojavelinux** [comment]
Oh, I see what you mean. Actually, I'm not too surprised it works because inside of Asciidoctor we normalize paths like crazy. So once it reads in the path, it resolves it down to a simple path and then processes it...at least, I'm pretty sure about that.
