### ISSUE TITLE
Support Bitbucket and GitLab

### ISSUE THREAD

**Issue by nawroth** [asciidoctor/docgist#20]
Have a look at both repos and snippets and see what could be supported.

Maybe some other hosts as well,  see:
https://git.wiki.kernel.org/index.php/GitHosting
https://en.wikipedia.org/wiki/Comparison_of_source_code_hosting_facilities

**Comment by mojavelinux** [comment]
:+1:

**Comment by nawroth** [comment]
Both require authorization to use their API, so it won't work unless we add a server part of DocGist.
As DocGist can do so much without a backend, I see no reason to create one at the moment.

**Comment by mojavelinux** [comment]
That's too bad. It's really unfortunate that neither of these allow public access to their API, esp GitLab. Win for GitHub.

**Comment by cmplstofB** [comment]
The situation has changed since then?

**Comment by mojavelinux** [comment]
This project is no longer active.
