### ISSUE TITLE
Support the stylesheet attribute

### ISSUE THREAD

**Issue by nawroth** [asciidoctor/docgist#25]
Also use the `stylesdir` attribute as well, if it has been set.

**Comment by nawroth** [comment]
See:

* http://gist.asciidoctor.org/?github-asciidoctor%2Fdocgist%2F%2Fgists%2Fexample.adoc&stylesheet=maker.css&no-header-footer
* http://gist.asciidoctor.org/?github-asciidoctor%2Fdocgist%2F%2Fgists%2Fexample.adoc&stylesheet=maker.css&no-header-footer

The stylesheet factory themes are available.
For now, `stylesdir` and `stylesheet` are simply concatenated.
We should be able to do smarter things with URLs though, for the next time around.
And maybe a dropdown to change the theme.

**Comment by mojavelinux** [comment]
:+1:
