### ISSUE TITLE
Google will discontinue the goo.gl on March 30, 2019

### ISSUE THREAD

**Issue by ftoh** [asciidoctor/docgist#34]
According to the [homepage](https://goo.gl/)
> Starting March 30, 2018, we will be turning down support for goo.gl URL shortener. From April 13, 2018 only existing users will be able to create short links on the goo.gl console. You will be able to view your analytics data and download your short link information in csv format for up to one year, until March 30, 2019, when we will discontinue goo.gl. Previously created links will continue to redirect to their intended destination. Please see this [blog post](https://developers.googleblog.com/2018/03/transitioning-google-url-shortener.html) for more details.

It is necessary to choose another URL shortener.

**Comment by mojavelinux** [comment]
How does that affect this project? Is it the fact that there's a share link in the header?

**Comment by FTOH** [comment]
To share the short link is one of the functions of this project, and it will cease to work soon. But it is not a critical problem.

**Comment by mojavelinux** [comment]
I agree it's not critical the function, though it would still be good to remove it. Would you like to submit a patch?
