### ISSUE TITLE
Document which URLs are supported

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/docgist#4]
Document which URLs are supported by DocGist, and how DocGist recognizes them.

**Comment by nawroth** [comment]
Added docs here: http://gist.asciidoctor.org/#source-documents

And here's a google doc as support went in for that as well:
http://gist.asciidoctor.org/?gdoc-1lEQTEAQRVxTtDfQ1N9HJ6azeOLYCKlGG17NOs72NWsU
